### ISSUE TITLE
main page: page build

### ISSUE THREAD

**Issue by Ye-kki** [Menjil-Menjil/Menjil-FE#28]
## 개발사항

메인페이지 구현

### 기능 명세

- [ ] 멘토 추천 뉴스피드
- [ ] 나의 프로필 카드
- [ ] 채팅 목록

### 테스트 항목

- [ ] 테스트 항목1
- [ ] 테스트 항목2

## 추가사항

추가적으로 알아야하는 사항을 작성해주세요.

**Comment by ninanoray** [comment]
깡통 구현 완료
